/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    HomePage: typeof import('./src/components/HomePage.vue')['default']
    IEpArrowDown: typeof import('~icons/ep/arrow-down')['default']
    IEpCalendar: typeof import('~icons/ep/calendar')['default']
    IEpChromeFilled: typeof import('~icons/ep/chrome-filled')['default']
    IEpExpand: typeof import('~icons/ep/expand')['default']
    IEpFold: typeof import('~icons/ep/fold')['default']
    IEpFullScreen: typeof import('~icons/ep/full-screen')['default']
    IEpHomeFilled: typeof import('~icons/ep/home-filled')['default']
    IEpLock: typeof import('~icons/ep/lock')['default']
    IEpMonitor: typeof import('~icons/ep/monitor')['default']
    IEpOrange: typeof import('~icons/ep/orange')['default']
    IEpPlatform: typeof import('~icons/ep/platform')['default']
    IEpRefresh: typeof import('~icons/ep/refresh')['default']
    IEpSetting: typeof import('~icons/ep/setting')['default']
    IEpShoppingBag: typeof import('~icons/ep/shopping-bag')['default']
    IEpShoppingCartFull: typeof import('~icons/ep/shopping-cart-full')['default']
    IEpUser: typeof import('~icons/ep/user')['default']
    IEpUserFilled: typeof import('~icons/ep/user-filled')['default']
    LoginPage: typeof import('./src/components/LoginPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    Welcome: typeof import('./src/components/welcome.vue')['default']
  }
}
